# Generated by Django 4.1.4 on 2023-10-28 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cos_cumparaturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_comanda', models.DateTimeField(auto_now_add=True)),
                ('livrata', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'cos_cumparaturii',
                'db_table': 'cos_cumparaturi',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nume', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Ingrediente',
                'db_table': 'ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nume', models.CharField(max_length=20)),
                ('pret', models.DecimalField(decimal_places=1, default=20, max_digits=4)),
                ('descriere', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Pizza',
                'db_table': 'pizza',
            },
        ),
        migrations.CreateModel(
            name='Pizzerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nume_pizzerie', models.CharField(max_length=50)),
                ('Locatie', models.CharField(max_length=50)),
                ('nr_telefon', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Pizzerie',
                'db_table': 'pizzerie',
            },
        ),
        migrations.CreateModel(
            name='Pizza_ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.ingrediente')),
                ('Pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.pizza')),
            ],
            options={
                'verbose_name_plural': 'Pizza Ingrediente',
                'db_table': 'pizza_ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Lista_favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.pizza')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lista Favorite',
                'db_table': 'lista_favorite',
            },
        ),
        migrations.CreateModel(
            name='Lista_comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Cos_cumparaturi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.cos_cumparaturi')),
                ('Pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.pizza')),
            ],
            options={
                'verbose_name_plural': 'lista_comenzi',
                'db_table': 'lista_comanda',
            },
        ),
        migrations.AddField(
            model_name='cos_cumparaturi',
            name='Pizzerie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.pizzerie'),
        ),
    ]
