# Generated by Django 4.1.4 on 2023-10-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_categorie_pizza_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='categorie',
        ),
    ]
