# Generated by Django 4.2.1 on 2023-11-04 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0003_remove_pizza_categorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name_plural': 'Categorii'},
        ),
        migrations.AlterModelOptions(
            name='cos_cumparaturi',
            options={'verbose_name_plural': 'Cos Cumparaturi'},
        ),
        migrations.RemoveField(
            model_name='cos_cumparaturi',
            name='Pizzerie',
        ),
        migrations.RemoveField(
            model_name='cos_cumparaturi',
            name='data_comanda',
        ),
        migrations.RemoveField(
            model_name='cos_cumparaturi',
            name='livrata',
        ),
        migrations.RemoveField(
            model_name='lista_comanda',
            name='Pizza',
        ),
        migrations.AddField(
            model_name='cos_cumparaturi',
            name='Pizza',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='hr.pizza'),
        ),
        migrations.AddField(
            model_name='cos_cumparaturi',
            name='User',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lista_comanda',
            name='livrata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lista_comanda',
            name='nr_comanda',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lista_comanda',
            name='Cos_cumparaturi',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='hr.cos_cumparaturi'),
        ),
        migrations.DeleteModel(
            name='Pizzerie',
        ),
    ]
