# Generated by Django 4.2.1 on 2023-11-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista_comanda',
            options={'verbose_name_plural': 'Lista Comenzi'},
        ),
    ]
