# Generated by Django 4.2.1 on 2023-11-19 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0007_cos_cumparaturi_nr_produse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AlterModelOptions(
            name='lista_comanda',
            options={'verbose_name_plural': 'lista_comenzi'},
        ),
        migrations.RemoveField(
            model_name='lista_comanda',
            name='Cos_cumparaturi',
        ),
        migrations.RemoveField(
            model_name='lista_comanda',
            name='nr_comanda',
        ),
        migrations.AddField(
            model_name='lista_comanda',
            name='CVV',
            field=models.CharField(default='XXX', max_length=40),
        ),
        migrations.AddField(
            model_name='lista_comanda',
            name='Pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.pizza'),
        ),
        migrations.AddField(
            model_name='lista_comanda',
            name='User',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lista_comanda',
            name='adresa',
            field=models.CharField(default='XXXXXXXXXXXX', max_length=40),
        ),
        migrations.AddField(
            model_name='lista_comanda',
            name='data_actualizare',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lista_comanda',
            name='data_cumparare',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lista_comanda',
            name='data_expirare',
            field=models.CharField(default='XX/XX', max_length=40),
        ),
        migrations.AddField(
            model_name='lista_comanda',
            name='nr_card',
            field=models.CharField(default='4242424242424242', max_length=16),
        ),
        migrations.AddField(
            model_name='lista_comanda',
            name='nr_produse',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='cos_cumparaturi',
            name='nr_produse',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
