# Generated by Django 4.2.1 on 2023-11-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_lista_comanda_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cos_cumparaturi',
            name='Pizza',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='hr.pizza'),
        ),
        migrations.AlterField(
            model_name='cos_cumparaturi',
            name='nr_produse',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
        ),
    ]
